name: Python Package using Conda

on: [push]

jobs:

  ubu:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      # conda activation requires bash instead of sh
      # 
      # C:\Miniconda\condabin\conda.bat init powershell
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: common_assets/conda_envs/nn_dl_python.yaml
          environment-name: nn_dl_python
      - name: Test imports
        run: |
          pip install pytest
          pytest --disable-warnings common_assets/conda_envs/test_imports.py
          
  win:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat install mamba -n base -c conda-forge
        C:\Miniconda\condabin\mamba env update --file common_assets/conda_envs/nn_dl_python_win.yaml --name nn_dl_python
        C:\Miniconda\condabin\conda.bat activate nn_dl_python
        python common_assets/conda_envs/test_imports.py
