name: Python Package using Conda

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      # conda activation requires bash instead of sh
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channel-priority: strict  
          activate-environment: nn_dl_python
          environment-file: common_assets/conda_envs/nn_dl_python.yaml
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Test imports
        run: |
          mamba install pytest
          pytest common_assets/conda_envs/test_imports.py
